import { BadRequestException, Injectable } from '@nestjs/common';
import { PaymentProvider, PaymentStatus } from '@visa-compass/shared';
import { OrdersService } from '../orders/orders.service.js';
import { EsewaGateway } from './gateways/esewa.gateway.js';
import { KhaltiGateway } from './gateways/khalti.gateway.js';
import { PaymentSimulatorGateway } from './gateways/simulator.gateway.js';

@Injectable()
export class PaymentsService {
  constructor(private orders: OrdersService, private khalti: KhaltiGateway, private esewa: EsewaGateway, private simulator: PaymentSimulatorGateway) {}
  async initiate(orderId: string, ownerId: string, provider: PaymentProvider) { const order = this.orders.get(orderId, ownerId); const returnUrl = `${process.env.CUSTOMER_WEB_URL ?? 'http://localhost:3000'}/esim/order/${orderId}`; const gateway = process.env.PAYMENT_MODE === 'sandbox' || process.env.NODE_ENV === 'production' ? (provider === PaymentProvider.KHALTI ? this.khalti : this.esewa) : this.simulator; const result = await gateway.initiate({ orderId, orderNumber: order.orderNumber, amountNpr: order.totalAmountNpr, returnUrl }); await this.orders.beginPayment(orderId, ownerId, provider, { ...result, returnUrl }); return result; }
  async verify(orderId:string,ownerId:string,reference:string){const order=this.orders.get(orderId,ownerId);const context=this.context(order,reference);const gateway=order.payment!.provider===PaymentProvider.KHALTI?this.khalti:this.esewa;const result=await gateway.verify(reference,context);if(result.status!==PaymentStatus.COMPLETED||result.orderId!==order.id||result.amountNpr!==order.totalAmountNpr)throw new BadRequestException(`Payment lookup did not confirm the order: ${result.status}`);return this.orders.confirmPayment(orderId,reference)}
  async verifyCallback(orderId:string,reference:string){const order=this.orders.get(orderId);const context=this.context(order,reference);if(order.payment!.status===PaymentStatus.COMPLETED)return this.orders.view(orderId);const gateway=order.payment!.provider===PaymentProvider.KHALTI?this.khalti:this.esewa;const result=await gateway.verify(reference,context);if(result.status!==PaymentStatus.COMPLETED||result.orderId!==order.id||result.amountNpr!==order.totalAmountNpr)throw new BadRequestException(`Payment lookup did not confirm the order: ${result.status}`);return this.orders.confirmPayment(orderId,reference)}
  async simulate(orderId: string, ownerId: string, reference: string, scenario: 'SUCCESS'|'CANCELLED'|'PENDING'|'WRONG_AMOUNT'|'REFUNDED'|'TIMEOUT' = 'SUCCESS') { if (process.env.NODE_ENV === 'production') throw new BadRequestException('Simulator is disabled'); if (scenario === 'TIMEOUT') throw new BadRequestException('Simulated payment provider timeout'); const order = this.orders.get(orderId, ownerId); const context=this.context(order,reference); this.simulator.apply(reference, scenario, context); const result = await this.simulator.verify(reference,context); if (result.status !== PaymentStatus.COMPLETED || result.orderId !== orderId || result.amountNpr !== order.totalAmountNpr) throw new BadRequestException(`Payment verification failed: ${result.status}`); return await this.orders.confirmPayment(orderId, reference); }
  private context(order:ReturnType<OrdersService['get']>,reference:string){if(order.payment?.reference!==reference)throw new BadRequestException('Payment reference mismatch');return {orderId:order.id,amountNpr:order.totalAmountNpr,...(order.payment.correlationId?{correlationId:order.payment.correlationId}:{})};}
}
