'use client';
import { useAuthenticatedFetch } from '../authenticated-api-provider';
import { useEffect,useRef,useState } from 'react';
import { AlertTriangle,CheckCircle2,FileUp,LoaderCircle,Upload,PackageCheck,PackageOpen,RefreshCcw } from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';
type Overview={counts:{available:number;reserved:number;assigned:number;activated:number};lowStockThreshold:number;lowStock:boolean;batches:{id:string;batchReference:string;totalProfiles:number;importedCount:number;failedCount:number;createdAt:string}[]};
type ImportResult={imported:number;skipped:number;errors?:string[];batch:string|null};

export default function InventoryClient(){const authFetch=useAuthenticatedFetch();
  const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),
    [iccids,setIccids]=useState(''),[source,setSource]=useState(''),[importing,setImporting]=useState(false),[notice,setNotice]=useState(''),
    [csvFile,setCsvFile]=useState<File|null>(null),[csvBusy,setCsvBusy]=useState(false),[csvNotice,setCsvNotice]=useState(''),[csvErrors,setCsvErrors]=useState<string[]>([]),
    csvInput=useRef<HTMLInputElement>(null);
  const load=()=>{void authFetch(`${API}/operations/inventory`,{headers:{}}).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error?.message);setData(v.data)}).catch(e=>setError(e.message))};
  useEffect(load,[]);
  const submit=async()=>{const list=iccids.split(/\n|,|;| /).map(s=>s.trim()).filter(Boolean);if(!list.length){setNotice('Paste at least one ICCID');return}setImporting(true);setNotice('');try{const r=await authFetch(`${API}/operations/inventory/import`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({iccids:list,source:source.trim()||undefined})});const v=await r.json();if(!r.ok)throw new Error(v.error?.message);setNotice(`Imported ${v.data.imported} profiles, skipped ${v.data.skipped} duplicate(s)`);setIccids('');load()}catch(e){setNotice(e instanceof Error?e.message:'Import failed')}finally{setImporting(false)}};
  const submitCsv=async()=>{if(!csvFile){setCsvNotice('Choose a CSV file first');return}setCsvBusy(true);setCsvNotice('');setCsvErrors([]);try{const csv=await csvFile.text();const r=await authFetch(`${API}/operations/inventory/import-csv`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({csv,source:source.trim()||undefined})});const v=await r.json();if(!r.ok)throw new Error(v.error?.message);const result=v.data as ImportResult;setCsvNotice(`Imported ${result.imported} profiles, skipped ${result.skipped} row(s)`);setCsvErrors(result.errors??[]);if(result.imported>0){setCsvFile(null);if(csvInput.current)csvInput.current.value=''}load()}catch(e){setCsvNotice(e instanceof Error?e.message:'CSV import failed')}finally{setCsvBusy(false)}};
  if(!data)return <div className="empty-table">{error||<><LoaderCircle className="spin"/>Loading inventory…</>}</div>;
  const metrics=[['Available',data.counts.available,PackageOpen],['Reserved',data.counts.reserved,RefreshCcw],['Assigned',data.counts.assigned,PackageCheck],['Activated',data.counts.activated,CheckCircle2]] as const;
  return <><div className="top"><div><h1>eSIM inventory</h1><p>Atomic reservations, single-use assignment, and batch traceability.</p></div><span className={`stock-state ${data.lowStock?'low':'healthy'}`}>{data.lowStock?<AlertTriangle size={15}/>:<CheckCircle2 size={15}/>} {data.lowStock?'Low stock':'Stock healthy'}</span></div><section className="grid">{metrics.map(([label,value,Icon])=><article className="metric" key={label}><span className="metric-label">{label}</span><div className="metric-row"><strong>{value}</strong><span className="icon"><Icon size={18}/></span></div></article>)}</section><div className="threshold-note">Low-stock alert triggers at {data.lowStockThreshold} available profiles.</div><section className="panel"><div className="panel-head"><h2>Import ICCIDs</h2><span>Paste Transatel ICCID inventory</span></div><div className="import-form"><textarea rows={5} placeholder={'Paste ICCIDs, one per line, e.g.\n899770100000000001\n899770100000000002'} value={iccids} onChange={(e)=>setIccids(e.target.value)}/><div className="import-actions"><input placeholder="Source (e.g. batch reference)" value={source} onChange={(e)=>setSource(e.target.value)}/><button onClick={submit} disabled={importing||!iccids.trim()}>{importing?<LoaderCircle className="spin" size={15}/>:<Upload size={15}/>} Import</button></div>{notice&&<div className="import-notice">{notice}</div>}</div></section><section className="panel"><div className="panel-head"><h2>Bulk upload profiles (CSV)</h2><span>Columns: iccid, eid (optional)</span></div><div className="import-form"><input ref={csvInput} type="file" accept=".csv,text/csv" onChange={(e)=>setCsvFile(e.target.files?.[0]??null)}/><div className="import-actions"><button onClick={submitCsv} disabled={csvBusy||!csvFile}>{csvBusy?<LoaderCircle className="spin" size={15}/>:<FileUp size={15}/>} Upload CSV</button></div>{csvNotice&&<div className="import-notice">{csvNotice}</div>}{csvErrors.length>0&&<div className="import-notice error">{csvErrors.slice(0,20).join(' · ')}{csvErrors.length>20&&` (+${csvErrors.length-20} more)`}</div>}</div></section><section className="panel"><div className="panel-head"><h2>Import batches</h2><span>{data.batches.length} batches</span></div>{data.batches.length===0?<div className="empty-table">No inventory batches imported yet.</div>:<div className="table-wrap"><table><thead><tr><th>Batch</th><th>Imported</th><th>Failed</th><th>Total</th><th>Created</th></tr></thead><tbody>{data.batches.map(batch=><tr key={batch.id}><td><b>{batch.batchReference}</b></td><td>{batch.importedCount}</td><td>{batch.failedCount}</td><td>{batch.totalProfiles}</td><td>{new Date(batch.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>}</section></>}
