import { describe,expect,it,vi } from 'vitest';
import { renderNotification } from './notification.templates.js';
const CUSTOM_TEMPLATES=['ORDER_STATUS','QR_READY','DOCUMENT_REUPLOAD','PLAN_EXHAUSTED','PLAN_EXPIRED'] as const;
describe('notification templates',()=>{
  it('does not expose QR credentials in the ready message',()=>{const value=renderNotification('QR_READY',{orderNumber:'VC-2026-TEST'});expect(value.text.toLowerCase()).toContain('attached as an image');expect(value.text.toLowerCase()).not.toContain('pdf');expect(value.text).not.toContain('LPA:');expect(value.html.toLowerCase()).not.toContain('lpa:')});
  it('includes the operator reason in a re-upload request',()=>{expect(renderNotification('DOCUMENT_REUPLOAD',{orderNumber:'VC-1',reason:'Image is blurred'}).text).toContain('Image is blurred')});
  it.each(CUSTOM_TEMPLATES)('renders a branded professional %s email', (template)=>{vi.stubEnv('SUPPORT_EMAIL','support@visacompass.example');try{const value=renderNotification(template,{orderNumber:'VC-2026-TEST'});expect(value.subject).toContain('Visa Compass');expect(value.text).toContain('Dear Customer,');expect(value.text).toContain('Warm regards,');expect(value.text).toContain('The Visa Compass Team');expect(value.text).toContain('VC-2026-TEST');expect(value.html).toContain('Visa Compass');expect(value.html).toContain('Dear Customer,');expect(value.html).toContain('mailto:');}finally{vi.unstubAllEnvs()}});
  it('greets the customer by name when available',()=>{const value=renderNotification('ORDER_STATUS',{orderNumber:'VC-1',customerName:'Bikash'});expect(value.text).toContain('Dear Bikash,');expect(value.text).not.toContain('Dear Customer,');expect(value.html).toContain('Dear Bikash,')});
  it('keeps operational alerts internal and actionable',()=>{const value=renderNotification('OPS_ALERT',{orderNumber:'VC-1',reason:'PROVISIONING_FAILED: retries exhausted'});expect(value.subject).toContain('[Visa Compass Ops]');expect(value.text).toContain('PROVISIONING_FAILED: retries exhausted');expect(value.text).not.toContain('Dear Customer,');expect(value.text).not.toContain('Warm regards,')});
  it('escapes html-sensitive characters in dynamic values',()=>{const value=renderNotification('DOCUMENT_REUPLOAD',{orderNumber:'VC-1',reason:'<b>blurry</b>'});expect(value.html).not.toContain('<b>blurry</b>');expect(value.html).toContain('&lt;b&gt;blurry&lt;/b&gt;')});
});
