"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { CheckCircle2, ExternalLink, RefreshCcw, XCircle } from "lucide-react";
import { toast } from "sonner";
import { useAuthenticatedFetch } from "../authenticated-api-provider";
import { PageHeader } from "@/components/page-header";
import { Panel } from "@/components/panel";
import { StatusBadge } from "@/components/status-badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

const API = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1";
export const REFUND_REASONS = ["PROVISIONING_FAILURE", "INCORRECT_FULFILLMENT", "DUPLICATE_CHARGE", "PROVIDER_SERVICE_FAILURE", "INTERNAL_OPERATIONAL_ERROR"] as const;
export type ManualRefund = { id:string; orderId:string; paymentId:string; status:"REQUESTED"|"APPROVED"|"COMPLETED"|"REJECTED"; reason:string; explanation:string; amount:number|string; providerReference?:string|null; reviewNote?:string|null; createdAt:string; order:{orderNumber:string;status:string}; requestedBy:{email:string}; reviewedBy?:{email:string}|null };

export default function ManualRefundsClient() {
  const authFetch = useAuthenticatedFetch();
  const [items,setItems]=useState<ManualRefund[]>([]); const [status,setStatus]=useState("ACTIVE"); const [busy,setBusy]=useState("");
  const [isSuperAdmin,setIsSuperAdmin]=useState(false);
  const load=useCallback(async()=>{ const query=status==="ACTIVE"?"":"?status="+status; const response=await authFetch(`${API}/operations/manual-refunds${query}`); const value=await response.json(); setItems((value.data?.items??[]).filter((item:ManualRefund)=>status!=="ACTIVE"||["REQUESTED","APPROVED"].includes(item.status))); },[authFetch,status]);
  useEffect(()=>{void load();void authFetch(`${API}/auth/me`).then(r=>r.json()).then(v=>setIsSuperAdmin(v.data?.accountType==="SUPER_ADMIN"))},[load,authFetch]);
  const act=async(item:ManualRefund, action:"approve"|"reject"|"complete")=>{ let body:Record<string,unknown>={}; if(action==="reject"){const note=window.prompt("Rejection note"); if(!note)return; body={note};} if(action==="approve") body={note:"Approved for manual completion in Khalti"}; if(action==="complete"){const providerReference=window.prompt("Khalti refund reference"); if(!providerReference)return;const completedAt=window.prompt("Completion date/time (ISO)",new Date().toISOString());if(!completedAt)return;const note=window.prompt("Optional evidence or completion note")??""; body={providerReference,amount:Number(item.amount),completedAt,...(note.trim()?{note:note.trim()}:{})};} setBusy(item.id+action); try{const response=await authFetch(`${API}/operations/manual-refunds/${item.id}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const value=await response.json();if(!response.ok)throw new Error(value.error?.message??"Action failed");toast.success(`Manual refund ${action}d`);await load();}catch(error){toast.error(error instanceof Error?error.message:"Action failed")}finally{setBusy("")}};
  return <><PageHeader title="Manual refunds" description="Rare company-fault refunds completed outside Visa Compass in Khalti." actions={<div className="flex gap-2"><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ACTIVE">Needs attention</SelectItem><SelectItem value="REQUESTED">Requested</SelectItem><SelectItem value="APPROVED">Approved</SelectItem><SelectItem value="COMPLETED">Completed</SelectItem><SelectItem value="REJECTED">Rejected</SelectItem></SelectContent></Select><Button variant="outline" onClick={()=>void load()}><RefreshCcw className="size-4"/>Refresh</Button></div>}/><Panel title="Refund register" description="Submitting or approving never sends money. Complete the refund in Khalti before confirming it here." noPadding><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Reason</TableHead><TableHead>Amount</TableHead><TableHead>Status</TableHead><TableHead>Requested by</TableHead><TableHead>Reference</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{items.map(item=><TableRow key={item.id}><TableCell><Link className="font-medium text-primary hover:underline" href={`/orders/${item.orderId}`}>{item.order.orderNumber}</Link></TableCell><TableCell><p>{item.reason.replaceAll("_"," ")}</p><p className="max-w-72 truncate text-xs text-muted-foreground">{item.explanation}</p></TableCell><TableCell>NPR {Number(item.amount).toLocaleString()}</TableCell><TableCell><StatusBadge label={item.status}/></TableCell><TableCell>{item.requestedBy.email}</TableCell><TableCell>{item.providerReference??"—"}</TableCell><TableCell><div className="flex justify-end gap-2">{isSuperAdmin&&item.status==="REQUESTED"&&<><Button size="sm" variant="success" disabled={!!busy} onClick={()=>void act(item,"approve")}><CheckCircle2 className="size-4"/>Approve</Button><Button size="sm" variant="outline" disabled={!!busy} onClick={()=>void act(item,"reject")}><XCircle className="size-4"/>Reject</Button></>}{isSuperAdmin&&item.status==="APPROVED"&&<Button size="sm" disabled={!!busy} onClick={()=>void act(item,"complete")}><ExternalLink className="size-4"/>Confirm completed</Button>}{!isSuperAdmin&&["REQUESTED","APPROVED"].includes(item.status)?<span className="text-xs text-muted-foreground">Super Admin action required</span>:null}</div></TableCell></TableRow>)}</TableBody></Table></Panel></>;
}
