'use client';
import { useAuthenticatedFetch } from '../authenticated-api-provider';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { LoaderCircle } from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';
export type OpsOrder={id:string;orderNumber:string;ownerId:string;status:string;createdAt:string;totalAmountNpr:number;plan:{name:string;countryCode:string};traveler?:{firstName:string;surname:string;email:string};purchaseType?:'INITIAL_PURCHASE'|'TOPUP';topUpMobile?:string};
export const opsHeaders={};
export default function OrdersClient({queueOnly=false}:{queueOnly?:boolean}){const authFetch=useAuthenticatedFetch();const [orders,setOrders]=useState<OpsOrder[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState('');useEffect(()=>{authFetch(`${API}/operations/orders`,{headers:opsHeaders}).then(r=>r.json()).then(v=>setOrders(v.data??[])).finally(()=>setLoading(false))},[]);const visible=orders.filter(o=>(!queueOnly||['REVIEW_PENDING','AWAITING_CUSTOMER','PROVISIONING_FAILED'].includes(o.status))&&`${o.orderNumber} ${o.traveler?.firstName??''} ${o.traveler?.surname??''}`.toLowerCase().includes(query.toLowerCase()));return <>{!queueOnly&&<div className="orders-toolbar"><input className="search" placeholder="Search orders…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{visible.length} orders</span></div>}<section className="panel">{queueOnly&&<div className="panel-head"><h2>Orders requiring attention</h2><span className="queue-count">{visible.length}</span></div>}{loading?<div className="empty-table"><LoaderCircle className="spin"/>Loading orders…</div>:visible.length===0?<div className="empty-table">No matching orders.</div>:<div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Destination</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(order=><tr key={order.id}><td><b>{order.orderNumber}</b><small>{new Date(order.createdAt).toLocaleDateString()}{order.topUpMobile?` · ${order.topUpMobile}`:''}</small></td><td>{order.traveler?`${order.traveler.firstName} ${order.traveler.surname}`:order.ownerId}</td><td>{order.plan.countryCode} · {order.plan.name}{order.purchaseType==='TOPUP'?<span className="pill topup">TOP-UP</span>:null}</td><td>NPR {order.totalAmountNpr.toLocaleString()}</td><td><span className={`pill ${order.status==='REVIEW_PENDING'?'green':''}`}>{order.status.replaceAll('_',' ')}</span></td><td><Link href={`/orders/${order.id}`}>Review →</Link></td></tr>)}</tbody></table></div>}</section></>}
