'use client';
import { useAuthenticatedFetch } from '../authenticated-api-provider';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Bell,LoaderCircle,RefreshCcw } from 'lucide-react';
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api/v1';
const headers={};
type Notification={id:string;orderId?:string;channel:string;template:string;status:string;sentAt?:string;createdAt:string};
export default function NotificationsClient(){const authFetch=useAuthenticatedFetch();const [items,setItems]=useState<Notification[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState('');const load=()=>authFetch(`${API}/operations/notifications`,{headers}).then(async response=>{const value=await response.json();if(!response.ok)throw new Error(value.error?.message);setItems(value.data)});useEffect(()=>{void load().catch(cause=>setError(cause.message)).finally(()=>setLoading(false))},[]);const retry=async(id:string)=>{setBusy(id);setError('');try{const response=await authFetch(`${API}/operations/notifications/${id}/retry`,{method:'POST',headers:{...headers,'x-idempotency-key':crypto.randomUUID()}});const value=await response.json();if(!response.ok)throw new Error(value.error?.message);await load()}catch(cause){setError(cause instanceof Error?cause.message:'Retry failed')}finally{setBusy('')}};if(loading)return <div className="empty-table"><LoaderCircle className="spin"/>Loading delivery attempts…</div>;return <section className="panel notification-panel">{error&&<div className="ops-error">{error}</div>}<div className="panel-head"><h2><Bell size={16}/>Delivery history</h2><span>{items.length} attempts</span></div>{items.length===0?<div className="empty-table">No notifications have been queued yet.</div>:<div className="table-wrap"><table><thead><tr><th>Created</th><th>Order</th><th>Channel</th><th>Template</th><th>Status</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{new Date(item.createdAt).toLocaleString()}</td><td>{item.orderId?<Link href={`/orders/${item.orderId}`}>View order</Link>:'—'}</td><td>{item.channel}</td><td>{item.template.replaceAll('_',' ')}</td><td><span className={`pill ${item.status==='SENT'?'green':item.status==='FAILED'?'red':''}`}>{item.status}</span></td><td>{item.status==='FAILED'&&<button className="notification-retry" disabled={busy===item.id} onClick={()=>retry(item.id)}><RefreshCcw className={busy===item.id?'spin':''} size={13}/>Retry</button>}</td></tr>)}</tbody></table></div>}</section>}
